### ISSUE TITLE
Login button does nothing - No module named 'aiohttp'

### ISSUE THREAD

**Issue by P4TMrls** [Roblox/roblox-blender-plugin#20] opened 2023-10-10 17:56 UTC
Hello, I am experiencing the same issue as losqe but I am unable to resolve it despite following the instructions.

_"When I click on log in in blender nothing happens, it says logging in but only while my cursor is over log in button and nothing else happens."_

Here's my toggle system console:

Read prefs: "C:\Users\jpmor\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
Traceback (most recent call last):
  File "C:\Users\jpmor\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\roblox-blender-plugin\lib\oauth2_login_operators.py", line 69, in on_login_complete
    task.result()
  File "C:\Users\jpmor\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\roblox-blender-plugin\lib\oauth2_client.py", line 168, in login
    import aiohttp.web as web
ModuleNotFoundError: No module named 'aiohttp'

**Comment by P4TMrls** [comment] 2023-10-10 21:22
@Nightriff

**Comment by Nightriff** [comment] 2023-10-12 18:18
Thanks for reporting. Missing `aiohttp` module indicates the dependencies didn't get installed properly. Could you try reinstalling the plugin and see if that fixes it for you? It should have an `Install Dependencies` button after installing, and make sure to check the system console for any errors during that installation. Once you see the "Installation complete, please restart" message, it should be successfully installed.

The login button shouldn't show without a successful dependency installation, so there may be a bug here.

**Comment by StarTheCodingFox** [comment] 2023-10-26 17:06
@Nightriff I tried reinstalling the plugin, but even that didn't work. Nothing happens.

**Comment by Nightriff** [comment] 2024-01-09 01:32
@StarTheCodingFox When you say "Nothing happens", is that when clicking Login button, or the Install Dependencies button? If it's during installation, could you please check for error output in the console after attempting the install?
To enable the console:
* On Windows, in Blender go to Window > Toggle System Console to see the console.
* On Mac OS, you'll need to start Blender from a terminal window.

**Comment by rdeusser** [comment] 2024-01-21 23:38
@StarTheCodingFox Try deleting this folder `%appdata%\Roaming\Blender Foundation\Blender\4.0\scripts\addons\roblox-blender-plugin\dependencies_public` and disabling and then re-enabling the plugin. It should say it needs to install dependencies. Do that and then restart Blender. I was having a similar issue to this one and this process fixed it.

**Comment by Nightriff** [comment] 2024-06-06 07:45
I'm going to close this issue as a duplicate. Please track resolution of the issue on ticket https://github.com/Roblox/roblox-blender-plugin/issues/42, which highlights the root cause

**Closed by Nightriff** 2024-06-06 07:45 UTC
Labels: bug, question
