### ISSUE TITLE
"Add-on Error" during upload: AttributeError: Calling operator "bpy.ops.export_scene.fbx" error, could not be found

### ISSUE THREAD

**Issue by TheoriginalNeko** [Roblox/roblox-blender-plugin#57] opened 2024-08-13 20:23 UTC
When I press upload it says in Upload Status Add-on error
![Screenshot 2024-08-13 162741](https://github.com/user-attachments/assets/3c364fbf-67fe-4fe6-b89d-d9b76533e5f9)

**Comment by Nightriff** [comment] 2024-08-21 22:23
To get more details about this error, can you share the console output during the upload attempt?

* On Windows, in Blender go to `Window` > `Toggle System Console` to see the console.
* On Mac OS, you'll need to start Blender from a terminal window.

**Comment by TheoriginalNeko** [comment] 2024-08-22 14:49
@Nightriff and @Autonvilkku Here is the Terminal stuff:

Read prefs: "C:\Users\Gamergodyt\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
Registered Power Sequencer with 72 modules
Reloading external rigs...
Reloading external metarigs...
register_class(...):
Info: Registering panel class: 'TEXTURE_PT_colors', bl_idname 'TEXTURE_PT_colors' has been registered before, unregistering previous
register_class(...):
Info: Registering operator class: 'OBJECT_OT_AlignOperator', bl_idname 'object.align' has been registered before, unregistering previous

To use POV centric workspaces you can set POV render option
and save it with File > Defaults > Save Startup File menu
Read blend: "C:\Users\Gamergodyt\OneDrive\Documents\untitled.blend"
Traceback (most recent call last):
  File "C:\Users\Gamergodyt\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\roblox-blender-plugin\lib\oauth2_login_operators.py", line 81, in on_refresh_complete
    task.result()
  File "C:\Users\Gamergodyt\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\roblox-blender-plugin\lib\oauth2_client.py", line 245, in refresh_login_if_needed
    new_token_data = await self.__refresh_tokens(refresh_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gamergodyt\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\roblox-blender-plugin\lib\oauth2_client.py", line 322, in __refresh_tokens
    raise exception
  File "C:\Users\Gamergodyt\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\roblox-blender-plugin\lib\oauth2_client.py", line 316, in __refresh_tokens
    response.raise_for_status()  # Raises ClientResponseError or other ClientError
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gamergodyt\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\roblox-blender-plugin\dependencies_public\aiohttp\client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Token has been revoked', url=URL('https://apis.roblox.com/oauth/v1/token')
Traceback (most recent call last):
  File "C:\Users\Gamergodyt\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\roblox-blender-plugin\lib\upload_operator.py", line 156, in upload
    export_fbx(scene, view_layer, target_object, exported_file_path, add_on_preferences)
  File "C:\Users\Gamergodyt\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\roblox-blender-plugin\lib\export_fbx.py", line 61, in export_fbx
    bpy.ops.export_scene.fbx(
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.export_scene.fbx" error, could not be found

**Comment by Nightriff** [comment] 2024-08-22 18:39
The `Token has been revoked` error is related to login; the add-on goes to refresh your token but Roblox's server says the refresh token was revoked, which happens after a fixed amount of time or when logging out. When encountering that error, the add-on should be re-prompting you to log in. Let me know if that didn't happen. In any case, you should be able to resolve that by logging out of the plugin and logging back in. 

But I see a second error, `bpy.ops.export_scene.fbx` operator could not be found. That seems unusual, and is likely the cause of the "Add-on error" message you're seeing. I'm unfortunately not able to reproduce this using Blender 4.1.1 (I see you're also on 4.1). 

Would you be able to take a screen recording of the upload process? I'm curious if there's anything unusual about your blender layout causing a wrong context to exist where the export_scene.fbx operator isn't available.

**Comment by TheoriginalNeko** [comment] 2024-08-23 13:10
Ok thanks I will send you it.

**Comment by TheoriginalNeko** [comment] 2024-08-23 16:47
I can't take a screen recording can you tell me more about "blender layout causing a wrong context to exist where the export_scene.fbx operator isn't available." Because that might be somthing thats causing it.

**Comment by TheoriginalNeko** [comment] 2024-08-23 16:49
Also I've tried to log out and log bag in before but it didn't do anything.

**Comment by TheoriginalNeko** [comment] 2024-08-23 17:16
I fixed it!

**Comment by Nightriff** [comment] 2024-08-28 06:07
@TheoriginalNeko I'm glad the issue was resolved for you. Did you figure out what fixed it, so that others who are experiencing this can also learn?

**Comment by Nightriff** [comment] 2024-10-10 18:18
Closing this since no further information was provided. Feel free to comment if there's more to add.

**Comment by PlasmaShield27** [comment] 2024-10-15 00:41
Im having trouble with this as well I was excited to see this only to discover that it never answered my question

**Comment by Nightriff** [comment] 2024-10-16 17:46
@PlasmaShield27 Thanks for adding your voice. To help diagnose, can you share the output from the console during the upload attempt?

* On Windows, in Blender go to `Window` > `Toggle System Console` to see the console.
* On Mac OS, you'll need to start Blender from a terminal window.

The more data points we have here, hopefully the closer we get to figuring out the cause.

**Comment by PlasmaShield27** [comment] 2024-10-16 21:47
ok I'll do that

Read blend: "C:\Users\charl\OneDrive\Documents\Sword 1.blend"

FBX export starting... 'C:\\Users\\charl\\AppData\\Local\\Temp\\tmpm4nqemr6\\Eye\\Gem.fbx'
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\__init__.py", line 596, in execute
    return export_fbx_bin.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3647, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3531, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\encode_bin.py", line 402, in write
    with open(fn, 'wb') as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\charl\\AppData\\Local\\Temp\\tmpm4nqemr6\\Eye\\Gem.fbx'
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\__init__.py", line 596, in execute
    return export_fbx_bin.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3647, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3531, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\BlendTraceback (most recent call last):
  File "C:\Users\charl\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\roblox-blender-plugin-main\lib\upload_operator.py", line 156, in upload
    export_fbx(scene, view_layer, target_object, exported_file_path, add_on_preferences)
  File "C:\Users\charl\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\roblox-blender-plugin-main\lib\export_fbx.py", line 61, in export_fbx
    bpy.ops.export_scene.fbx(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\__init__.py", line 596, in execute
    return export_fbx_bin.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3647, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3531, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\encode_bin.py", line 402, in write
    with open(fn, 'wb') as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\charl\\AppData\\Local\\Temp\\tmpm4nqemr6\\Eye\\Gem.fbx'
Location: C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\modules\bpy\ops.py:109

... truncated
FBX export starting... 'C:\\Users\\charl\\AppData\\Local\\Temp\\tmpf0_a5hcq\\Eye\\Gem.fbx'
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\__init__.py", line 596, in execute
    return export_fbx_bin.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3647, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3531, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\encode_bin.py", line 402, in write
    with open(fn, 'wb') as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\charl\\AppData\\Local\\Temp\\tmpf0_a5hcq\\Eye\\Gem.fbx'
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\__init__.py", line 596, in execute
    return export_fbx_bin.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3647, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3531, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\BlendTraceback (most recent call last):
  File "C:\Users\charl\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\roblox-blender-plugin-main\lib\upload_operator.py", line 156, in upload
    export_fbx(scene, view_layer, target_object, exported_file_path, add_on_preferences)
  File "C:\Users\charl\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\roblox-blender-plugin-main\lib\export_fbx.py", line 61, in export_fbx
    bpy.ops.export_scene.fbx(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\__init__.py", line 596, in execute
    return export_fbx_bin.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3647, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3531, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\addons_core\io_scene_fbx\encode_bin.py", line 402, in write
    with open(fn, 'wb') as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\charl\\AppData\\Local\\Temp\\tmpf0_a5hcq\\Eye\\Gem.fbx'
Location: C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.2.0_x64__ppwjx1n5r4v9t\Blender\4.2\scripts\modules\bpy\ops.py:109

**Comment by PlasmaShield27** [comment] 2024-10-16 21:49
sorry it's a lot and I don't know a lot about coding in python

I do see a file not found error and a runtime error

**Comment by PlasmaShield27** [comment] 2024-10-16 22:01
FYI i tried reinstalling the add on

**Comment by Nightriff** [comment] 2024-10-17 00:49
Thanks for the output @PlasmaShield27 

I think in your case, the problem is due to the slash `/` in the object name causing a problem with the export because it thinks the `Eye` is a folder on the file system rather than part of the file name. 

If you rename your object to not have a slash in it, it should export with no problem.

I'll create an issue to sanitize the file name to avoid exporting to the file system with a bad file name.

**Comment by Nightriff** [comment] 2024-10-17 01:00
Since `Add-on Error` can be caused by multiple things, I'm going to start separating issues based on the cause of the Add-on Error. 

Adjusted the title of this issue to reflect the original error message for this post.

Closing again since this issue does not have enough information to diagnose and I can't reproduce the error.

Feel free to comment if you have something further to add related to `AttributeError: Calling operator "bpy.ops.export_scene.fbx" error, could not be found`

If you have an `Add-on Error` message but a different error reason in the output, please open a new issue.

**Closed by Nightriff** 2024-10-17 01:00 UTC
Labels: bug, question, can't reproduce

**Comment by PlasmaShield27** [comment] 2024-10-17 22:09
Thank you it worked!
