### ISSUE TITLE
ModuleNotFoundError: No module named 'roblox-blender-plugin-1'

### ISSUE THREAD

**Issue by dragonclassepk** [Roblox/roblox-blender-plugin#39] opened 2023-12-18 17:34 UTC
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'roblox-blender-plugin-1'

**Comment by dragonclassepk** [comment] 2023-12-18 17:35
Could not find nothing on how to fix this, sorry if this wastes your time.

**Comment by Nightriff** [comment] 2024-01-09 00:46
Thanks for reporting - I'm not sure what would cause this error, because `roblox-blender-plugin-1` isn't an import anywhere in the code base. That indicates to me that something is going wrong during installation, perhaps the plugin folder is getting renamed due to a duplicate installation?

My best advice here is to do a full uninstall of any versions and reinstall.
1. Follow the steps to [uninstall the plugin](https://github.com/Roblox/roblox-blender-plugin#uninstall-old-version) from the readme page. 
2. After closing Blender, double check your plugin folder in file explorer (On Windows, you can go to `%AppData%\Blender Foundation\Blender\4.0\scripts\addons`), and delete any folders that are named `roblox-blender-plugin` or similar
3. Open Blender, and go back to Edit > Preferences > Add-ons and verify the plugin does not show up in the list
4. Follow the steps to [download and install the latest version of the plugin ](https://github.com/Roblox/roblox-blender-plugin#install-new-version)from the readme page. 
* During installation, check for errors in the console output. On Windows, in Blender go to `Window` > `Toggle System Console` to see the console. On Mac OS, you'll need to start Blender from a terminal window.

After completing these steps, please report back if you're still experiencing the same issue, and include any relevant errors from the console output during installation if present!

**Comment by Nightriff** [comment] 2024-10-10 18:20
Closing this since I can't reproduce the issue. Please comment if there's anything further to add.

**Closed by Nightriff** 2024-10-10 18:20 UTC
Labels: bug, question, can't reproduce
