### ISSUE TITLE
Cant upload/select Collections 

### ISSUE THREAD

**Issue by EngyneMac** [Roblox/roblox-blender-plugin#36] opened 2023-11-27 10:12 UTC
the add-on now only detects meshes and not collections. This kind of makes the add-on unusable once you go on studio since the packages tab shows all sorts of meshes unorganized. 

![image](https://github.com/Roblox/roblox-blender-plugin/assets/150859697/aedb69c9-2852-4b58-97ca-0addb6832b26)
![image](https://github.com/Roblox/roblox-blender-plugin/assets/150859697/de8ea206-9fe6-4c38-b223-d03c046edd3e)

**Comment by Nightriff** [comment] 2024-01-09 00:49
I'm unable to reproduce this on the latest version of the plugin (v1.0.3 at the time of writing). I'm closing this issue, but please comment to let me know if you're still experiencing this!

**Closed by Nightriff** 2024-01-09 00:49 UTC
Labels: bug, can't reproduce
