### ISSUE TITLE
400 Bad Request during upload: Failed to read the request form. Request body too large. The max request body size is 30000000 bytes.

### ISSUE THREAD

**Issue by l4kms** [Roblox/roblox-blender-plugin#65] opened 2024-09-22 05:37 UTC
idk what is that
![image](https://github.com/user-attachments/assets/3eb50e2a-a729-4fca-80aa-08f2f35e9b15)

**Comment by Nightriff** [comment] 2024-09-23 15:52
The important error there is this:
> Failed to read the request form. Request body too large. The max request body size is 30000000 bytes

The most likely cause sounds like the car model being uploaded is too large, it must be under 28.6 megabytes according to that error message.

**Comment by Nightriff** [comment] 2024-10-10 18:21
Closing this since no further information was provided and it seems to be working as intended.

**Closed by Nightriff** 2024-10-10 18:21 UTC
Labels: question, out of scope, working as intended
