### ISSUE TITLE
Exporting from Blender does not get imported to Roblox

### ISSUE THREAD

**Issue by VoiditeDev** [Roblox/roblox-blender-plugin#47] opened 2024-04-29 19:29 UTC
Whenever I press "Upload", It doesn't upload at all, I put everything properly, I can't record a video because my recorder refuses to focus on multiple apps but these screenshots below should _hopefully_ help you with the issues.

![image](https://github.com/Roblox/roblox-blender-plugin/assets/142426954/56299819-ac57-404c-a573-57e9fa237b10)

![image](https://github.com/Roblox/roblox-blender-plugin/assets/142426954/51fcaf8c-9aee-42fe-a62c-33e7ead767a5)

**Comment by Nightriff** [comment] 2024-05-03 00:38
Can you check the version number in that "Upload success" message by dragging the edge of the add-on window to the left to expand it?

I'm wondering if you previously published this item under a different name, and now it's updating one of those existing packages in your screenshot without you realizing it.

You can also check the asset ID it's updating by looking at the `Roblox Package ID` field in the custom properties of the selected mesh. You can look up this asset on the creator marketplace to figure out where it's located, too. Swap in the asset ID you find into this URL: `https://create.roblox.com/dashboard/creations/store/YOUR_ASSET_ID/configure`

**Comment by VoiditeDev** [comment] 2024-05-03 07:31
> I'm wondering if you previously published this item under a different name, and now it's updating one of those existing packages in your screenshot without you realizing it.

It was at the same name, I didn't previously publish the item under a different name

> Can you check the version number in that "Upload success" message by dragging the edge of the add-on window to the left to expand it?

I did this again for a test and it successfully does the job

![image](https://github.com/Roblox/roblox-blender-plugin/assets/142426954/eecdc909-36b8-4cce-af39-83e360e609ce)

![image](https://github.com/Roblox/roblox-blender-plugin/assets/142426954/f59d6fd7-734f-4555-acef-13a63cea8a06)

> You can also check the asset ID it's updating by looking at the `Roblox Package ID` field in the custom properties of the selected mesh. You can look up this asset on the creator marketplace to figure out where it's located, too. Swap in the asset ID you find into this URL: `https://create.roblox.com/dashboard/creations/store/YOUR_ASSET_ID/configure`

I found the asset ID and it is working fine

![image](https://github.com/Roblox/roblox-blender-plugin/assets/142426954/3bcb6eee-a7d8-45c8-b00d-254e8f5102db)

**Comment by Nightriff** [comment] 2024-06-06 07:30
Okay, if I understand correctly, everything is working for you now. I'll close this issue as can't reproduce, feel free to comment again to re-open it if you're still experiencing an issue here.

**Closed by Nightriff** 2024-06-06 07:30 UTC
Labels: bug, question
